---
version: "3"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "make start-backend"
    env_file:
      - backend/.env
    ports:
      - "5001:5001"
    volumes:
      # - ~/.bash_history:/root/.bash_history
      # - .:${WORKING_DIRECTORY}
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
    depends_on:
      - postgres
volumes:
  pgdata:
