name: On Release

on:
  push:
    tags:
      - v*

jobs:

  build:
    if: github.repository == 'hexlet-rus/runit'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v3
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: hexlet-editor
          heroku_email: ${{secrets.HEROKU_EMAIL}}
